kind: Service
apiVersion: v1
metadata:
  name: logstash
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: logstash
  ports:  
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: logstash
